<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UmamusumeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $umamusumeData = [
            // Agnes Tachyon
            [
                'id' => 'agnes_tachyon',
                'name' => 'Agnes Tachyon',
                'nickname' => 'The Uncrowned Genius',
                'team' => 'Canopus',
                'release_batch' => 'Launch',
                'cv' => 'Yuuko Iida',
                'birthday' => 'April 13',
                'height_cm' => 159,
                'weight' => 'Perfectly standard',
                'three_sizes' => ['bust' => 83, 'waist' => 54, 'hips' => 82],
                'images' => ['avatar' => 'uploads/trainee_images/__agnes_tachyon_umamusume_drawn_by_welchino__sample-1db2ca428e2545fcae81fe526d7a8e96.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 10, 'stamina' => 0, 'power' => 0, 'guts' => 0, 'wisdom' => 20],
                'aptitudes' => ['terrain' => ['turf' => 'A', 'dirt' => 'G'], 'distance' => ['sprint' => 'F', 'mile' => 'A', 'medium' => 'A', 'long' => 'A'], 'strategy' => ['front' => 'B', 'leader' => 'A', 'chaser' => 'A', 'end' => 'C']],
                'base_stats' => ['speed' => 93, 'stamina' => 89, 'power' => 93, 'guts' => 93, 'wisdom' => 102],
                'unique_skill' => ['name' => 'Code: Tachyon', 'effect' => 'Increases acceleration in the final leg if running mid-pack.'],
                'skills' => ['initial' => [['name' => 'Position Sense', 'type' => 'yellow', 'rank' => 'B']], 'awakening' => [['star' => 2, 'name' => 'Genius’s Insight', 'type' => 'green', 'rank' => 'A'], ['star' => 3, 'name' => 'Theory of Victory', 'type' => 'yellow', 'rank' => 'SS']]],
                'career_goals' => [['race' => 'Satsuki Sho', 'requirement' => 'Top 5'], ['race' => 'Tokyo Yushun (Japanese Derby)', 'requirement' => 'Top 5'], ['race' => 'Tenno Sho (Autumn)', 'requirement' => 'Top 3'], ['race' => 'Arima Kinen', 'requirement' => '1st']],
                'tags' => ['mile', 'medium', 'long', 'leader', 'canopus'],
                'ui' => ['frame_color' => '#33CCFF', 'icon' => 'icons/wisdom.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umapyoi.fandom.com/wiki/Agnes_Tachyon', 'game8' => 'https://game8.jp/umamusume/character/Agnes_Tachyon'],
            ],
            // Daiwa Scarlet
            [
                'id' => 'daiwa_scarlet',
                'name' => 'Daiwa Scarlet',
                'nickname' => 'Resplendent Red Ace',
                'team' => 'Spica',
                'release_batch' => 'Launch',
                'cv' => 'Keiko Watanabe',
                'birthday' => 'May 13',
                'height_cm' => 163,
                'weight' => 'Slight increase',
                'three_sizes' => ['bust' => 90, 'waist' => 56, 'hips' => 82],
                'images' => ['avatar' => 'uploads/trainee_images/__daiwa_scarlet_umamusume_drawn_by_kurokawa_heuy__sample-9576ae268cdddfe167c2300d5453f2cf.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 10, 'stamina' => 0, 'power' => 0, 'guts' => 20, 'wisdom' => 0],
                'aptitudes' => ['terrain' => ['turf' => 'A', 'dirt' => 'G'], 'distance' => ['sprint' => 'F', 'mile' => 'A', 'medium' => 'A', 'long' => 'A'], 'strategy' => ['front' => 'A', 'leader' => 'A', 'chaser' => 'E', 'end' => 'G']],
                'base_stats' => ['speed' => 89, 'stamina' => 103, 'power' => 84, 'guts' => 117, 'wisdom' => 131],
                'unique_skill' => ['name' => 'Resplendent Red Ace', 'effect' => 'Greatly increases speed in the final straight when racing in front.'],
                'skills' => ['initial' => [['name' => 'Frontline Dash', 'type' => 'yellow', 'rank' => 'A']], 'awakening' => [['star' => 2, 'name' => 'Angling for Position', 'type' => 'yellow', 'rank' => 'A'], ['star' => 3, 'name' => 'Scarlet Turbo', 'type' => 'yellow', 'rank' => 'SS']]],
                'career_goals' => [['race' => 'Tulip Sho', 'requirement' => 'Top 5'], ['race' => 'Oka Sho', 'requirement' => 'Top 5'], ['race' => 'Japanese Oaks', 'requirement' => 'Top 5'], ['race' => 'Shuka Sho', 'requirement' => 'Top 3'], ['race' => 'Queen Elizabeth II Cup', 'requirement' => 'Top 3'], ['race' => 'Osaka Hai', 'requirement' => 'Top 3'], ['race' => 'Tenno Sho (Autumn)', 'requirement' => '1st'], ['race' => 'Arima Kinen', 'requirement' => '1st']],
                'tags' => ['mile', 'medium', 'long', 'leader', 'spica'],
                'ui' => ['frame_color' => '#FF4D4D', 'icon' => 'icons/speed.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umapyoi.fandom.com/wiki/Daiwa_Scarlet', 'game8' => 'https://game8.jp/umamusume/character/Daiwa_Scarlet'],
            ],
            // El Condor Pasa
            [
                'id' => 'el_condor_pasa',
                'name' => 'El Condor Pasa',
                'nickname' => 'El Número Uno',
                'team' => null,
                'release_batch' => 'Launch',
                'cv' => 'Minami Takahashi',
                'birthday' => 'March 17',
                'height_cm' => 163,
                'weight' => null,
                'three_sizes' => ['bust' => 89, 'waist' => 58, 'hips' => 86],
                'images' => ['avatar' => 'uploads/trainee_images/__el_condor_pasa_umamusume_drawn_by_nekogusa_kinako__85cfefb3697093d2c40c9db031ab46a5.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 2,
                'growth_rates' => ['speed' => 20, 'wisdom' => 10],
                'aptitudes' => ['terrain' => ['turf' => 'A', 'dirt' => null], 'distance' => null, 'strategy' => null],
                'base_stats' => ['speed' => 85, 'stamina' => 76, 'power' => 80, 'guts' => 93, 'wisdom' => 91],
                'unique_skill' => null,
                'skills' => null,
                'career_goals' => null,
                'tags' => ['versatile', 'dancer', 'dirt-friendly'],
                'ui' => ['frame_color' => '#ffeeaa', 'icon' => 'icons/speed.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/El_Condor_Pasa', 'game8' => null],
            ],
            // Gold Ship
            [
                'id' => 'gold_ship',
                'name' => 'Gold Ship',
                'nickname' => "Tracen's Greatest Mischief-Maker",
                'team' => 'Spica',
                'release_batch' => 'Launch',
                'cv' => 'Hitomi Ueda',
                'birthday' => 'March 6',
                'height_cm' => 170,
                'weight' => 'Immeasurable',
                'three_sizes' => ['bust' => 88, 'waist' => 55, 'hips' => 88],
                'images' => ['avatar' => 'uploads/trainee_images/__gold_ship_umamusume_drawn_by_advarcher__sample-2713426899554240b99dc00440e97745.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['stamina' => 20, 'power' => 10],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'G', 'mile' => 'C', 'medium' => 'A', 'long' => 'A'],
                    'strategy' => ['front' => 'C', 'leader' => 'B', 'chaser' => 'A', 'end' => 'A'],
                ],
                'base_stats' => ['speed' => 80, 'stamina' => 100, 'power' => 90, 'guts' => 110, 'wisdom' => 80],
                'unique_skill' => ['name' => 'Winning the Soul', 'effect' => 'Greatly increases speed in the final leg if running in the back.'],
                'skills' => [
                    'initial' => [['name' => 'Stamina Keeper', 'type' => 'blue', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Late Charge', 'type' => 'red', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unpredictable', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Satsuki Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Kikka Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Takarazuka Kinen', 'requirement' => 'Top 3'],
                    ['race' => 'Arima Kinen', 'requirement' => '1st'],
                ],
                'tags' => ['long-distance', 'chaser', 'spica'],
                'ui' => ['frame_color' => '#ffd700', 'icon' => 'icons/stamina.png', 'pentagon_chart' => true],
                'links' => [
                    'wiki' => 'https://umamusume.fandom.com/wiki/Gold_Ship',
                    'game8' => null,
                ],
            ],
            // Haru Urara
            [
                'id' => 'haru_urara',
                'name' => 'Haru Urara',
                'nickname' => 'Shining Loser',
                'team' => null,
                'release_batch' => 'Launch',
                'cv' => 'Yukina Shutō',
                'birthday' => 'February 27',
                'height_cm' => 140,
                'weight' => null,
                'three_sizes' => ['bust' => 74, 'waist' => 51, 'hips' => 73],
                'images' => ['avatar' => 'uploads/trainee_images/__haru_urara_umamusume_drawn_by_advarcher__sample-7d1c3c431ef193e5e061bdda73f97fd5.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 1,
                'growth_rates' => ['guts' => 20, 'power' => 10],
                'aptitudes' => ['terrain' => ['turf' => 'G', 'dirt' => 'A'], 'distance' => ['sprint' => 'A', 'mile' => 'B', 'medium' => 'G', 'long' => 'G'], 'strategy' => ['leader' => 'G', 'front' => 'F', 'chaser' => 'A', 'end' => 'D']],
                'base_stats' => ['speed' => 83, 'stamina' => 58, 'power' => 89, 'guts' => 86, 'wisdom' => 84],
                'unique_skill' => null,
                'skills' => null,
                'career_goals' => null,
                'tags' => ['dirt-sprinter', 'underdog'],
                'ui' => ['frame_color' => '#ffbcd9', 'icon' => 'icons/guts.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Haru_Urara', 'game8' => null],
            ],
            // Maruzensky
            [
                'id' => 'maruzensky',
                'name' => 'Maruzensky',
                'nickname' => 'Supercar',
                'team' => 'Team Rigil',
                'release_batch' => 'Launch',
                'cv' => 'Lynn',
                'birthday' => 'May 19',
                'height_cm' => 164,
                'weight' => 'Totally tubular!',
                'three_sizes' => ['bust' => 92, 'waist' => 58, 'hips' => 88],
                'images' => ['avatar' => 'uploads/trainee_images/__maruzensky_umamusume_drawn_by_kamishima_kanon__sample-297ecca0da3990374954a514f06bea2b.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 20, 'power' => 10],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'A', 'mile' => 'A', 'medium' => 'B', 'long' => 'G'],
                    'strategy' => ['front' => 'A', 'leader' => 'A', 'chaser' => 'C', 'end' => 'E'],
                ],
                'base_stats' => ['speed' => 96, 'stamina' => 68, 'power' => 86, 'guts' => 100, 'wisdom' => 100],
                'unique_skill' => ['name' => 'Kindan Burning Heart', 'effect' => 'Greatly increases speed in the final straight when leading.'],
                'skills' => [
                    'initial' => [['name' => 'Front Runner', 'type' => 'yellow', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Speed Star', 'type' => 'yellow', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unlimited Impact', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Spring Stakes', 'requirement' => 'Top 5'],
                    ['race' => 'Asahi Hai Futurity Stakes', 'requirement' => 'Top 3'],
                    ['race' => 'Japanese Derby', 'requirement' => 'Top 3'],
                ],
                'tags' => ['sprinter', 'front-runner', 'rigil'],
                'ui' => ['frame_color' => '#ff66cc', 'icon' => 'icons/speed.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Maruzensky', 'game8' => null],
            ],
            // Narita Brian (update avatar path)
            [
                'id' => 'narita_brian',
                'name' => 'Narita Brian',
                'nickname' => 'Maverick',
                'team' => 'Team Sirius',
                'release_batch' => 'Launch',
                'cv' => 'Rika Kinugawa',
                'birthday' => 'May 3',
                'height_cm' => 160,
                'weight' => 'Standard',
                'three_sizes' => ['bust' => 91, 'waist' => 58, 'hips' => 85],
                'images' => ['avatar' => 'uploads/trainee_images/__narita_brian_and_biwa_hayahide_umamusume_drawn_by_hitoto__sample-e1edfe57e7e12f49d5a724698f738783.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 10, 'stamina' => 20],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'G', 'mile' => 'B', 'medium' => 'A', 'long' => 'A'],
                    'strategy' => ['front' => 'C', 'leader' => 'B', 'chaser' => 'A', 'end' => 'A'],
                ],
                'base_stats' => ['speed' => 93, 'stamina' => 89, 'power' => 100, 'guts' => 89, 'wisdom' => 79],
                'unique_skill' => ['name' => 'Maverick Drive', 'effect' => 'Greatly increases speed in the final leg if running in the back.'],
                'skills' => [
                    'initial' => [['name' => 'Stamina Keeper', 'type' => 'blue', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Late Charge', 'type' => 'red', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unpredictable', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Satsuki Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Kikka Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Arima Kinen', 'requirement' => '1st'],
                ],
                'tags' => ['long-distance', 'chaser', 'sirius'],
                'ui' => ['frame_color' => '#44bbff', 'icon' => 'icons/stamina.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Narita_Brian', 'game8' => null],
            ],
            // Biwa Hayahide (update avatar path)
            [
                'id' => 'biwa_hayahide',
                'name' => 'Biwa Hayahide',
                'nickname' => 'Winning Equation',
                'team' => null,
                'release_batch' => 'Launch',
                'cv' => 'Yui Kondou',
                'birthday' => 'March 10',
                'height_cm' => 171,
                'weight' => 'Standard',
                'three_sizes' => ['bust' => 93, 'waist' => 61, 'hips' => 88],
                'images' => ['avatar' => 'uploads/trainee_images/__narita_brian_and_biwa_hayahide_umamusume_drawn_by_hitoto__sample-e1edfe57e7e12f49d5a724698f738783_cropped.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['stamina' => 20, 'wisdom' => 10],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'G', 'mile' => 'C', 'medium' => 'A', 'long' => 'A'],
                    'strategy' => ['front' => 'C', 'leader' => 'B', 'chaser' => 'A', 'end' => 'A'],
                ],
                'base_stats' => ['speed' => 85, 'stamina' => 93, 'power' => 82, 'guts' => 93, 'wisdom' => 97],
                'unique_skill' => ['name' => 'Winning Equation', 'effect' => 'Greatly increases stamina in the final leg if running in the back.'],
                'skills' => [
                    'initial' => [['name' => 'Stamina Keeper', 'type' => 'blue', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Late Charge', 'type' => 'red', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unpredictable', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Satsuki Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Kikka Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Arima Kinen', 'requirement' => '1st'],
                ],
                'tags' => ['long-distance', 'chaser'],
                'ui' => ['frame_color' => '#99cc66', 'icon' => 'icons/stamina.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Biwa_Hayahide', 'game8' => null],
            ],
            // Oguri Cap (update avatar path)
            [
                'id' => 'oguri_cap',
                'name' => 'Oguri Cap',
                'nickname' => 'Silver Legend',
                'team' => null,
                'release_batch' => 'Launch',
                'cv' => 'Tomoyo Takayanagi',
                'birthday' => 'March 27',
                'height_cm' => 167,
                'weight' => 'Standard',
                'three_sizes' => ['bust' => 82, 'waist' => 57, 'hips' => 82],
                'images' => ['avatar' => 'uploads/trainee_images/__oguri_cap_and_jacques_villeneuve_umamusume_and_1_more_drawn_by_holeecrab__sample-9628095fc1e0ee5bcc8c96c47d5722a1.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 20, 'power' => 10],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'G', 'mile' => 'B', 'medium' => 'A', 'long' => 'A'],
                    'strategy' => ['front' => 'C', 'leader' => 'B', 'chaser' => 'A', 'end' => 'A'],
                ],
                'base_stats' => ['speed' => 101, 'stamina' => 66, 'power' => 106, 'guts' => 84, 'wisdom' => 93],
                'unique_skill' => ['name' => 'Silver Legend', 'effect' => 'Greatly increases speed in the final leg if running in the back.'],
                'skills' => [
                    'initial' => [['name' => 'Power Runner', 'type' => 'yellow', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Late Charge', 'type' => 'red', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unpredictable', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Satsuki Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Kikka Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Arima Kinen', 'requirement' => '1st'],
                ],
                'tags' => ['long-distance', 'chaser'],
                'ui' => ['frame_color' => '#cccccc', 'icon' => 'icons/power.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Oguri_Cap', 'game8' => null],
            ],
            // Tokai Teio (update avatar path)
            [
                'id' => 'tokai_teio',
                'name' => 'Tokai Teio',
                'nickname' => 'Peak Joy',
                'team' => null,
                'release_batch' => 'Launch',
                'cv' => 'Machico',
                'birthday' => 'April 20',
                'height_cm' => 150,
                'weight' => 'Standard',
                'three_sizes' => ['bust' => 77, 'waist' => 54, 'hips' => 76],
                'images' => ['avatar' => 'uploads/trainee_images/__tokai_teio_umamusume_drawn_by_so_on__305c01834a0c0cf3fe3593c281a0b05b.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 3,
                'growth_rates' => ['speed' => 10, 'stamina' => 10],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'F', 'mile' => 'E', 'medium' => 'A', 'long' => 'B'],
                    'strategy' => ['front' => 'D', 'leader' => 'A', 'chaser' => 'C', 'end' => 'E'],
                ],
                'base_stats' => ['speed' => 90, 'stamina' => 89, 'power' => 83, 'guts' => 92, 'wisdom' => 96],
                'unique_skill' => ['name' => 'Teio Step', 'effect' => 'Greatly increases speed in the final leg when leading.'],
                'skills' => [
                    'initial' => [['name' => 'Front Runner', 'type' => 'yellow', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Speed Star', 'type' => 'yellow', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Unlimited Impact', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Satsuki Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Kikka Sho', 'requirement' => 'Top 5'],
                    ['race' => 'Arima Kinen', 'requirement' => '1st'],
                ],
                'tags' => ['medium-to-long', 'turf-specialist'],
                'ui' => ['frame_color' => '#88aaff', 'icon' => 'icons/speed.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Tokai_Teio', 'game8' => null],
            ],
            // Vodka (update avatar path)
            [
                'id' => 'vodka',
                'name' => 'Vodka',
                'nickname' => 'The Unconventional Empress',
                'team' => 'Spica',
                'release_batch' => 'Launch',
                'cv' => 'Ayaka Ōhashi',
                'birthday' => 'April 4',
                'height_cm' => 165,
                'weight' => 'Standard',
                'three_sizes' => ['bust' => 76, 'waist' => 55, 'hips' => 78],
                'images' => ['avatar' => 'uploads/trainee_images/__vodka_umamusume_drawn_by_mayata__41166bfaeb2670ae37c8785af4566d58.jpg', 'full' => null, 'cropped' => null, 'source' => 'fanart'],
                'rarity' => 2,
                'growth_rates' => ['speed' => 10, 'power' => 20],
                'aptitudes' => [
                    'terrain' => ['turf' => 'A', 'dirt' => 'G'],
                    'distance' => ['sprint' => 'F', 'mile' => 'A', 'medium' => 'A', 'long' => 'F'],
                    'strategy' => ['front' => 'C', 'leader' => 'B', 'chaser' => 'A', 'end' => 'F'],
                ],
                'base_stats' => ['speed' => 96, 'stamina' => 61, 'power' => 105, 'guts' => 75, 'wisdom' => 88],
                'unique_skill' => ['name' => 'Xceleration', 'effect' => 'Moderately increases speed when positioned toward the front with 200 m or less remaining when challenging rivals.'],
                'skills' => [
                    'initial' => [['name' => 'Straightaway Recovery', 'type' => 'yellow', 'rank' => 'A']],
                    'awakening' => [
                        ['star' => 2, 'name' => 'Straightaway Acceleration', 'type' => 'yellow', 'rank' => 'A'],
                        ['star' => 3, 'name' => 'Breath of Fresh Air', 'type' => 'yellow', 'rank' => 'SS'],
                    ],
                ],
                'career_goals' => [
                    ['race' => 'Mile Championship', 'requirement' => 'Top 5'],
                    ['race' => 'Victoria Mile', 'requirement' => 'Top 3'],
                    ['race' => 'Japan Cup', 'requirement' => '1st'],
                ],
                'tags' => ['mile', 'medium', 'late-surger', 'spica'],
                'ui' => ['frame_color' => '#AA77CC', 'icon' => 'icons/power.png', 'pentagon_chart' => true],
                'links' => ['wiki' => 'https://umamusume.fandom.com/wiki/Vodka', 'game8' => null],
            ],
        ];

        foreach ($umamusumeData as $data) {
            \App\Models\Umamusume::updateOrCreate(['id' => $data['id']], $data);
        }
    }
}
